# Generated by Django 5.0.4 on 2024-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_items_fooditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='restaurantName',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
