# Generated by Django 5.0.4 on 2024-05-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='foodItems',
        ),
    ]
