# Generated by Django 5.0.4 on 2024-05-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_fooditems_restaurantname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='restaurantName',
            field=models.CharField(max_length=50),
        ),
    ]
